{{- range $apps := .Values.apps }}
{{- $appname := $apps.name| trunc 63 | trimSuffix "-" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appname }}
  labels:
    app.kubernetes.io/instance: {{ $appname }}
    app.kubernetes.io/name: {{ $appname }}
spec:

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $appname }}
      app.kubernetes.io/name: {{ $appname }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: {{ $appname }}
        app.kubernetes.io/name: {{ $appname }}
    spec:
      containers:
        - name: {{ $apps.name }}
          image: "{{ $apps.image }}:{{ $apps.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
{{- end }}
